//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace me.bellacall.Core.Locales {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("me.bellacall.Core.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль.
        /// </summary>
        public static string AspNetRole_Entity {
            get {
                return ResourceManager.GetString("AspNetRole_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роли.
        /// </summary>
        public static string AspNetRole_List {
            get {
                return ResourceManager.GetString("AspNetRole_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешение.
        /// </summary>
        public static string AspNetRolePermission_Entity {
            get {
                return ResourceManager.GetString("AspNetRolePermission_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешения.
        /// </summary>
        public static string AspNetRolePermission_List {
            get {
                return ResourceManager.GetString("AspNetRolePermission_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт.
        /// </summary>
        public static string AspNetUser_Entity {
            get {
                return ResourceManager.GetString("AspNetUser_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунты.
        /// </summary>
        public static string AspNetUser_List {
            get {
                return ResourceManager.GetString("AspNetUser_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция.
        /// </summary>
        public static string AspNetUserLog_Entity {
            get {
                return ResourceManager.GetString("AspNetUserLog_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал операций.
        /// </summary>
        public static string AspNetUserLog_List {
            get {
                return ResourceManager.GetString("AspNetUserLog_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль аккаунта.
        /// </summary>
        public static string AspNetUserRole_Entity {
            get {
                return ResourceManager.GetString("AspNetUserRole_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роли аккаунта.
        /// </summary>
        public static string AspNetUserRole_List {
            get {
                return ResourceManager.GetString("AspNetUserRole_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кампания.
        /// </summary>
        public static string Campaign_Entity {
            get {
                return ResourceManager.GetString("Campaign_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кампании.
        /// </summary>
        public static string Campaign_List {
            get {
                return ResourceManager.GetString("Campaign_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} содержит [{1}]. Удаление недопустимо..
        /// </summary>
        public static string Cascade_Message {
            get {
                return ResourceManager.GetString("Cascade_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиент.
        /// </summary>
        public static string Company_Entity {
            get {
                return ResourceManager.GetString("Company_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты.
        /// </summary>
        public static string Company_List {
            get {
                return ResourceManager.GetString("Company_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списание средств.
        /// </summary>
        public static string CompanyExpense_Entity {
            get {
                return ResourceManager.GetString("CompanyExpense_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списания средств.
        /// </summary>
        public static string CompanyExpense_List {
            get {
                return ResourceManager.GetString("CompanyExpense_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начисление средств.
        /// </summary>
        public static string CompanyIncome_Entity {
            get {
                return ResourceManager.GetString("CompanyIncome_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начисления средств.
        /// </summary>
        public static string CompanyIncome_List {
            get {
                return ResourceManager.GetString("CompanyIncome_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакт.
        /// </summary>
        public static string Contact_Entity {
            get {
                return ResourceManager.GetString("Contact_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string Contact_List {
            get {
                return ResourceManager.GetString("Contact_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа контактов.
        /// </summary>
        public static string ContactGroup_Entity {
            get {
                return ResourceManager.GetString("ContactGroup_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группы контактов.
        /// </summary>
        public static string ContactGroup_List {
            get {
                return ResourceManager.GetString("ContactGroup_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойство контакта.
        /// </summary>
        public static string ContactProperty_Entity {
            get {
                return ResourceManager.GetString("ContactProperty_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойства контакта.
        /// </summary>
        public static string ContactProperty_List {
            get {
                return ResourceManager.GetString("ContactProperty_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кампании.
        /// </summary>
        public static string DbContext_Campaigns {
            get {
                return ResourceManager.GetString("DbContext_Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты.
        /// </summary>
        public static string DbContext_Companies {
            get {
                return ResourceManager.GetString("DbContext_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты - Списания средств.
        /// </summary>
        public static string DbContext_CompanyExpenses {
            get {
                return ResourceManager.GetString("DbContext_CompanyExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты - Начисления средств.
        /// </summary>
        public static string DbContext_CompanyIncomes {
            get {
                return ResourceManager.GetString("DbContext_CompanyIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кампании - Группы контактов.
        /// </summary>
        public static string DbContext_ContactGroups {
            get {
                return ResourceManager.GetString("DbContext_ContactGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники - DEF-коды.
        /// </summary>
        public static string DbContext_DEFs {
            get {
                return ResourceManager.GetString("DbContext_DEFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кампании - Шлюзы.
        /// </summary>
        public static string DbContext_Gateways {
            get {
                return ResourceManager.GetString("DbContext_Gateways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кампании - Рассылки.
        /// </summary>
        public static string DbContext_Jobs {
            get {
                return ResourceManager.GetString("DbContext_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кампании - Лиды.
        /// </summary>
        public static string DbContext_Leads {
            get {
                return ResourceManager.GetString("DbContext_Leads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники - Перенесенные номера.
        /// </summary>
        public static string DbContext_MNPs {
            get {
                return ResourceManager.GetString("DbContext_MNPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники - Операторы связи.
        /// </summary>
        public static string DbContext_Providers {
            get {
                return ResourceManager.GetString("DbContext_Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники - Регионы.
        /// </summary>
        public static string DbContext_Regions {
            get {
                return ResourceManager.GetString("DbContext_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники - Роли.
        /// </summary>
        public static string DbContext_Roles {
            get {
                return ResourceManager.GetString("DbContext_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кампании - Сценарии.
        /// </summary>
        public static string DbContext_Scripts {
            get {
                return ResourceManager.GetString("DbContext_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники - Тарифы.
        /// </summary>
        public static string DbContext_Tariffs {
            get {
                return ResourceManager.GetString("DbContext_Tariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты - Аккаунты - Журнал операций.
        /// </summary>
        public static string DbContext_UserLogs {
            get {
                return ResourceManager.GetString("DbContext_UserLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты - Аккаунты - Роли.
        /// </summary>
        public static string DbContext_UserRoles {
            get {
                return ResourceManager.GetString("DbContext_UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты - Аккаунты.
        /// </summary>
        public static string DbContext_Users {
            get {
                return ResourceManager.GetString("DbContext_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DEF-код.
        /// </summary>
        public static string DEF_Entity {
            get {
                return ResourceManager.GetString("DEF_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DEF-коды.
        /// </summary>
        public static string DEF_List {
            get {
                return ResourceManager.GetString("DEF_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шлюз.
        /// </summary>
        public static string Gateway_Entity {
            get {
                return ResourceManager.GetString("Gateway_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шлюзы.
        /// </summary>
        public static string Gateway_List {
            get {
                return ResourceManager.GetString("Gateway_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поток.
        /// </summary>
        public static string GatewayStream_Entity {
            get {
                return ResourceManager.GetString("GatewayStream_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Потоки.
        /// </summary>
        public static string GatewayStream_List {
            get {
                return ResourceManager.GetString("GatewayStream_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сценарий коллбэка.
        /// </summary>
        public static string InboxScript_Entity {
            get {
                return ResourceManager.GetString("InboxScript_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сценарии коллбэка.
        /// </summary>
        public static string InboxScript_List {
            get {
                return ResourceManager.GetString("InboxScript_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рассылка.
        /// </summary>
        public static string Job_Entity {
            get {
                return ResourceManager.GetString("Job_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рассылки.
        /// </summary>
        public static string Job_List {
            get {
                return ResourceManager.GetString("Job_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакт.
        /// </summary>
        public static string JobContact_Entity {
            get {
                return ResourceManager.GetString("JobContact_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string JobContact_List {
            get {
                return ResourceManager.GetString("JobContact_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сценарий рассылки.
        /// </summary>
        public static string JobScript_Entity {
            get {
                return ResourceManager.GetString("JobScript_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сценарии рассылки.
        /// </summary>
        public static string JobScript_List {
            get {
                return ResourceManager.GetString("JobScript_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лид.
        /// </summary>
        public static string Lead_Entity {
            get {
                return ResourceManager.GetString("Lead_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лиды.
        /// </summary>
        public static string Lead_List {
            get {
                return ResourceManager.GetString("Lead_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакт.
        /// </summary>
        public static string LeadContact_Entity {
            get {
                return ResourceManager.GetString("LeadContact_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string LeadContact_List {
            get {
                return ResourceManager.GetString("LeadContact_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойство лида.
        /// </summary>
        public static string LeadProperty_Entity {
            get {
                return ResourceManager.GetString("LeadProperty_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойства лида.
        /// </summary>
        public static string LeadProperty_List {
            get {
                return ResourceManager.GetString("LeadProperty_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенесенный номер.
        /// </summary>
        public static string MNP_Entity {
            get {
                return ResourceManager.GetString("MNP_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенесенные номера.
        /// </summary>
        public static string MNP_List {
            get {
                return ResourceManager.GetString("MNP_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление.
        /// </summary>
        public static string Operation_Create {
            get {
                return ResourceManager.GetString("Operation_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        public static string Operation_Delete {
            get {
                return ResourceManager.GetString("Operation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение.
        /// </summary>
        public static string Operation_Execute {
            get {
                return ResourceManager.GetString("Operation_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр.
        /// </summary>
        public static string Operation_Read {
            get {
                return ResourceManager.GetString("Operation_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение.
        /// </summary>
        public static string Operation_Update {
            get {
                return ResourceManager.GetString("Operation_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет прав на выполнение операции [{0}] в таблице [{1}]. Обратитесь к администратору..
        /// </summary>
        public static string Permission_Message {
            get {
                return ResourceManager.GetString("Permission_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор связи.
        /// </summary>
        public static string Provider_Entity {
            get {
                return ResourceManager.GetString("Provider_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операторы связи.
        /// </summary>
        public static string Provider_List {
            get {
                return ResourceManager.GetString("Provider_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регион.
        /// </summary>
        public static string Region_Entity {
            get {
                return ResourceManager.GetString("Region_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регионы.
        /// </summary>
        public static string Region_List {
            get {
                return ResourceManager.GetString("Region_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сценарий.
        /// </summary>
        public static string Script_Entity {
            get {
                return ResourceManager.GetString("Script_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сценарии.
        /// </summary>
        public static string Script_List {
            get {
                return ResourceManager.GetString("Script_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условный переход.
        /// </summary>
        public static string ScriptCondition_Entity {
            get {
                return ResourceManager.GetString("ScriptCondition_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условные переходы.
        /// </summary>
        public static string ScriptCondition_List {
            get {
                return ResourceManager.GetString("ScriptCondition_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элемент.
        /// </summary>
        public static string ScriptElement_Entity {
            get {
                return ResourceManager.GetString("ScriptElement_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элементы.
        /// </summary>
        public static string ScriptElement_List {
            get {
                return ResourceManager.GetString("ScriptElement_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входной параметр.
        /// </summary>
        public static string ScriptInputParameter_Entity {
            get {
                return ResourceManager.GetString("ScriptInputParameter_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входные параметры.
        /// </summary>
        public static string ScriptInputParameter_List {
            get {
                return ResourceManager.GetString("ScriptInputParameter_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выходной параметр.
        /// </summary>
        public static string ScriptOutputParameter_Entity {
            get {
                return ResourceManager.GetString("ScriptOutputParameter_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выходные параметры.
        /// </summary>
        public static string ScriptOutputParameter_List {
            get {
                return ResourceManager.GetString("ScriptOutputParameter_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойство.
        /// </summary>
        public static string ScriptProperty_Entity {
            get {
                return ResourceManager.GetString("ScriptProperty_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойства.
        /// </summary>
        public static string ScriptProperty_List {
            get {
                return ResourceManager.GetString("ScriptProperty_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переменная.
        /// </summary>
        public static string ScriptVariable_Entity {
            get {
                return ResourceManager.GetString("ScriptVariable_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переменные.
        /// </summary>
        public static string ScriptVariable_List {
            get {
                return ResourceManager.GetString("ScriptVariable_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тариф.
        /// </summary>
        public static string Tariff_Entity {
            get {
                return ResourceManager.GetString("Tariff_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тарифы.
        /// </summary>
        public static string Tariff_List {
            get {
                return ResourceManager.GetString("Tariff_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условие.
        /// </summary>
        public static string TariffCondition_Entity {
            get {
                return ResourceManager.GetString("TariffCondition_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условия.
        /// </summary>
        public static string TariffCondition_List {
            get {
                return ResourceManager.GetString("TariffCondition_List", resourceCulture);
            }
        }
    }
}
